ethereum_rpc = "https://rpc.ankr.com/eth_hoodi/59bbe30bcbfd3a4dcf644818bf8c75f5857f3c6875704c51ebf3bc773ff1bc01"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.LiquidityMirageTrap]
path = "out/LiquidityMirageTrap.sol/LiquidityMirageTrap.json"
response_contract = "0x8bf02296573a1349f0446f34f6c4851e887d3ae0"
response_function = "respondToMirage(bytes)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x2f597988051Ca1FB6986f661c825ff5217B1d03e"]
address = "0x67f60fe5878F60F110D584c90713a3eb076C8810"

